apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret  # secret.yaml dosyasi ile olusturlan mysecret secret objesinden al.
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret   # secret.yaml dosyasi ile olusturlan mysecret secret objesinden al.
            key: password
  restartPolicy: Never