apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=   # echo -n 'admin' | base64 komutu sonucu cikan cikti.
  password: MWYyZDFlMmU2N2Rm  #  # echo -n 'a1f2d1e2e67df' | base64 komutu sonucu cikan cikti.