apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name:  demo
          image: clarusway/demo:hello-config-file  # imaj daha onceki imajlardan farkli.
          ports:
            - containerPort: 8888
          volumeMounts:
          - mountPath: /config/            # root dizininde config diye bir dosya olusutur
            name: demo-config-volume       # baglanan volume ismi.
            readOnly: true
          resources: {}  
      volumes:
      - name: demo-config-volume
        configMap:
          name: demo-config
          items:
          - key: config                   # demo-config icerisindeki key=config olan datayi al volume bagladigim yerde demo.yaml isminde bir dosya olustur ve onun icine kopyala demek.
            path: demo.yaml