apiVersion: v1
kind: Pod
metadata:
  name: forcurl  # curl  atmak icin olusturulmustur.
spec:
  containers:
  - name: forcurl
    image: clarusway/forping
    imagePullPolicy: IfNotPresent
  restartPolicy: Always  