apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      labels:
        name: mongo
        app: todoapp
    spec:
      containers:
      - image: mongo:5.0
        name: mongo
        ports:
        - containerPort: 27017
        volumeMounts:             
          - name: mongo-storage     # ismini kendimiz verdik. Volume ismi.
            mountPath: /data/db     # Monogdb'nin kaydettigi dosylari mongo-storage volume'une bagla. Burasida pvc'ye baglanacak. Dizin Docker-hub'tan alindi. 
        resources: {}  
      volumes:
        # - name: mongo-storage
        #   hostPath:
        #    path: /home/ubuntu/pv-data  # Suradan geliyor --> db-pv.yaml > hosthPath > path: 
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim  # Suradan geliyor --> db-pvc.yaml > metadata: database-persistent-volume-claim